#!/usr/bin/env python3
"""Pure spectral root calculation for linear-in-E word relations q(C_L,C_R)E=0."""
from __future__ import annotations
import itertools,numpy as np
roots=np.array([-np.sqrt(3),-np.sqrt(2),-1,1,np.sqrt(2),np.sqrt(3)])
def mons(D):return [(a,b) for s in range(D+1) for a in range(s+1) for b in [s-a]]
def evalmat(D,diag=False):
 M=mons(D);pts=[(x,y) for x in roots for y in roots if (x==y if diag else abs(x-y)>1e-12)]
 A=np.array([[x**a*y**b for a,b in M] for x,y in pts]);return A,M,pts
def null(A,tol=1e-10):
 U,s,Vh=np.linalg.svd(A,full_matrices=True);r=int(np.sum(s>tol*s[0]));return Vh[r:].T,r,s
def polyvec(M,terms):
 ix={ab:i for i,ab in enumerate(M)};v=np.zeros(len(M))
 for ab,c in terms.items():v[ix[ab]]+=c
 return v
def p_terms(var):
 # x^6 -6x^4+11x^2-6
 return {((6,0) if var=='x' else (0,6)):1,((4,0) if var=='x' else (0,4)):-6,((2,0) if var=='x' else (0,2)):11,(0,0):-6}
def pdiv_terms():
 # (p(x)-p(y))/(x-y) = sum x^{n-1-j}y^j for n terms
 t={}
 for n,c in [(6,1),(4,-6),(2,11)]:
  for j in range(n):t[(n-1-j,j)]=t.get((n-1-j,j),0)+c
 return t
def main():
 for D in [5,6,7]:
  A,M,pts=evalmat(D);N,r,s=null(A);print('degree',D,'monomials',len(M),'offdiag_constraints',len(pts),'rank',r,'nullity',N.shape[1],'tail',s[-5:])
  # Known polynomials available within degree D: pdiv*x^k/y^k and p(x),p(y) when degree permits.
  known=[];names=[];pd=pdiv_terms()
  for a in range(D-5+1):
   for b in range(D-5-a+1):
    t={(i+a,j+b):c for (i,j),c in pd.items()};known.append(polyvec(M,t));names.append(f'x^{a}y^{b} pdiv')
  if D>=6:
   for base_name,base in [('p(x)',p_terms('x')),('p(y)',p_terms('y'))]:
    for a in range(D-6+1):
     for b in range(D-6-a+1):
      t={(i+a,j+b):c for (i,j),c in base.items()};known.append(polyvec(M,t));names.append(f'x^{a}y^{b} {base_name}')
  K=np.column_stack(known) if known else np.zeros((len(M),0));rk=np.linalg.matrix_rank(K,tol=1e-10*np.linalg.svd(K,compute_uv=False)[0]) if K.size else 0
  # how much nullspace remains after known spectral-polynomial family
  Uk,sk,Vhk=np.linalg.svd(K,full_matrices=False) if K.size else (np.zeros((len(M),0)),np.array([]),None);Qk=Uk[:,:rk] if rk else np.zeros((len(M),0));X=N-Qk@(Qk.T@N);sx=np.linalg.svd(X,compute_uv=False);extra=int(np.sum(sx>1e-8))
  print(' known_rank',rk,'extra_null_dim',extra,'known_names',names)
  if D<=7: assert extra==0
 print('PASS: on the complete ordered off-diagonal curl-root set, every degree<=7 linear-in-mother vanishing polynomial is generated by p(x), p(y), the divided difference p^{[1]}(x,y), and their allowed polynomial multiples. Therefore the extra physical word relation cannot come from roots/multiplicities alone.')
if __name__=='__main__':main()
