#!/usr/bin/env python3
"""The extra degree-7 linear-in-E relation should come from physical active spectral edges, not roots alone."""
from __future__ import annotations
import importlib.util,pathlib,itertools,numpy as np
ROOT=pathlib.Path(__file__).resolve().parents[3]
def load(name,file):
 p=ROOT/'core'/'curved_formation_signature'/'audits'/file;s=importlib.util.spec_from_file_location(name,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
mu=load('mu','metric_lie_spectral_unification.py')

def mons(D):return [(a,s-a) for s in range(D+1) for a in range(s+1)]
def pdiv_terms():
 t={}
 for n,c in [(6,1),(4,-6),(2,11)]:
  for j in range(n):t[(n-1-j,j)]=t.get((n-1-j,j),0)+c
 return t
def p_terms(var):return {((6,0) if var=='x' else (0,6)):1,((4,0) if var=='x' else (0,4)):-6,((2,0) if var=='x' else (0,2)):11,(0,0):-6}
def vec(M,t):
 ix={ab:i for i,ab in enumerate(M)};v=np.zeros(len(M))
 for ab,c in t.items():v[ix[ab]]+=c
 return v
def known_space(M):
 pd=pdiv_terms();cols=[]
 for a,b in [(0,0),(1,0),(0,1)]:cols.append(vec(M,{(i+a,j+b):c for (i,j),c in pd.items()}))
 cols.extend([vec(M,p_terms('x')),vec(M,p_terms('y'))]);K=np.column_stack(cols);U,s,Vh=np.linalg.svd(K,full_matrices=False);r=int(np.sum(s>1e-10*s[0]));return U[:,:r],r

def word_extra(C,E):
 # Degree<=7 numerical nullspace modulo two-sided ideal generated by p and Dp.
 labs=[''.join(x) for k in range(8) for x in itertools.product('CE',repeat=k)];ix={w:i for i,w in enumerate(labs)}
 mats=[np.eye(C.shape[0])];prev=[mats[0]]
 for _ in range(7):
  cur=[]
  for A in prev:cur.extend([A@C,A@E])
  mats.extend(cur);prev=cur
 W=np.column_stack([A.reshape(-1) for A in mats]);Uw,s,Vh=np.linalg.svd(W,full_matrices=False);r=int(np.sum(s>1e-10*s[0]));N=Vh[r:].T
 # base rels
 r1={'':-6,'CC':11,'CCCC':-6,'CCCCCC':1};r2={}
 for n,c in [(6,1),(4,-6),(2,11)]:
  for j in range(n):r2['C'*j+'E'+'C'*(n-1-j)]=r2.get('C'*j+'E'+'C'*(n-1-j),0)+c
 cols=[]
 for rr in (r1,r2):
  for la in range(2):
   for lb in range(2-la):
    for aa in itertools.product('CE',repeat=la):
     for bb in itertools.product('CE',repeat=lb):
      a=''.join(aa);b=''.join(bb);v=np.zeros(len(labs))
      for t,c in rr.items():v[ix[a+t+b]]+=c
      cols.append(v)
 I=np.column_stack(cols);Ui,si,Vhi=np.linalg.svd(I,full_matrices=False);ri=int(np.sum(si>1e-10*si[0]));Qi=Ui[:,:ri];X=N-Qi@(Qi.T@N);ux,sx,vx=np.linalg.svd(X,full_matrices=False);z=ux[:,0]
 # extract only one-E polynomial coefficients q(row-root,col-root)
 M=mons(6);q=np.zeros(len(M));mix={ab:i for i,ab in enumerate(M)}
 for coeff,lab in zip(z,labs):
  if lab.count('E')==1:
   pos=lab.index('E');a=pos;b=len(lab)-pos-1
   if a+b<=6:q[mix[(a,b)]]+=coeff
 return q/np.linalg.norm(q)

def main():
 data=mu.build_physical_tensors(False);C=data['C'];_,Es=mu.mother_tensor(data['Gamma'],C);vals,U=np.linalg.eigh((C+C.T)/2);groups=[]
 for i,x in enumerate(vals):
  if not groups or abs(x-groups[-1][0])>1e-8:groups.append([float(x),[i]])
  else:groups[-1][1].append(i)
 Ehs=[U.T@E@U for E in Es];active=[];inactive=[]
 for a,(x,I) in enumerate(groups):
  for b,(y,J) in enumerate(groups):
   if a==b:continue
   strength=np.sqrt(sum(np.linalg.norm(Eh[np.ix_(I,J)])**2 for Eh in Ehs))
   (active if strength>1e-10 else inactive).append((x,y,strength,a,b))
 print('root multiplicities',[(round(x,6),len(I)) for x,I in groups]);print('active ordered root edges',len(active),'inactive',len(inactive));print('inactive pairs',[(round(x,6),round(y,6)) for x,y,s,a,b in inactive])
 M=mons(6);A=np.array([[x**i*y**j for i,j in M] for x,y,*_ in active]);Ua,s,Vh=np.linalg.svd(A,full_matrices=True);r=int(np.sum(s>1e-10*s[0]));N=Vh[r:].T;Qk,rk=known_space(M);X=N-Qk@(Qk.T@N);ux,sx,vx=np.linalg.svd(X,full_matrices=False);extra=int(np.sum(sx>1e-8));qinc=ux[:,0]/np.linalg.norm(ux[:,0]);print('active_incidence degree6 monomials',len(M),'constraints',len(active),'rank',r,'nullity',N.shape[1],'known_rank',rk,'extra_dim',extra,'extra_singulars',sx[:5])
 rng=np.random.default_rng(29300);cos=[]
 for seed in range(4):
  a=rng.normal(size=28);E=sum(a[i]*Es[i] for i in range(28));qw=word_extra(C,E);cc=abs(np.dot(qw,qinc));cos.append(cc);print('seed',seed,'word_relation_vs_active_incidence_cosine',cc,'active_eval_res',np.linalg.norm(A@qw)/max(np.linalg.norm(A),1e-30))
 assert len(inactive)>0 and extra==1 and min(cos)>.999999
 print('PASS: the universal extra degree-7 mother relation is exactly the unique additional degree-6 polynomial vanishing on the physically active curl-sheet edges. It is not a root-only identity; it records Navier-Stokes interaction incidence/selection rules inside the C,E word algebra.')
if __name__=='__main__':main()
