#!/usr/bin/env python3
from __future__ import annotations
import importlib.util,pathlib,numpy as np
ROOT=pathlib.Path(__file__).resolve().parents[3]
def loadpath(name,p):
 s=importlib.util.spec_from_file_location(name,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
mu=loadpath('mu',ROOT/'core'/'curved_formation_signature'/'audits'/'metric_lie_spectral_unification.py')
ex=loadpath('ex',ROOT/'research'/'theory2_universal_compiler'/'audits'/'extract_degree7_new_relation.py')
def word_rank(C,E,L=7):
 W=ex.words(C,E,L);s=np.linalg.svd(W,compute_uv=False);return int(np.sum(s>1e-10*s[0])),W.shape[1],s
def ideal_rank(L=7):
 labs=ex.labels(L);I=ex.ideal(L,labs);s=np.linalg.svd(I,compute_uv=False);return int(np.sum(s>1e-10*s[0]))
def full_offblock_control(C,seed):
 rng=np.random.default_rng(seed);vals,U=np.linalg.eigh((C+C.T)/2);groups=[]
 for i,x in enumerate(vals):
  if not groups or abs(x-groups[-1][0])>1e-8:groups.append([float(x),[i]])
  else:groups[-1][1].append(i)
 Eh=np.zeros_like(C)
 for a,(x,I) in enumerate(groups):
  for b in range(a+1,len(groups)):
   J=groups[b][1];B=rng.normal(size=(len(I),len(J)));Eh[np.ix_(I,J)]=B;Eh[np.ix_(J,I)]=B.T
 return U@Eh@U.T

def main():
 data=mu.build_physical_tensors(False);C=data['C'];_,Es=mu.mother_tensor(data['Gamma'],C);rng=np.random.default_rng(29500);ri=ideal_rank();print('known_two_sided_ideal_rank_degree7',ri)
 physical=[];control=[]
 for seed in range(6):
  a=rng.normal(size=28);Ep=sum(a[i]*Es[i] for i in range(28));rp,n,sp=word_rank(C,Ep);Ec=full_offblock_control(C,29600+seed);rc,_,sc=word_rank(C,Ec);physical.append(n-rp);control.append(n-rc);print('seed',seed,'physical_nullity',n-rp,'full_offblock_control_nullity',n-rc,'physical_extra',n-rp-ri,'control_extra',n-rc-ri,'control_tail',sc[-10:])
 assert physical==[9]*6 and control==[8]*6 and ri==8
 print('PASS: with identical curl roots and multiplicities, a generic mother using all off-sheet blocks has exactly the eight relations generated by p(C), Dp_C(E) and their degree-7 consequences. The ninth relation exists only for the physical NS mother support, so it records interaction selection rather than spectral multiplicity alone.')
if __name__=='__main__':main()
